### PR TITLE
Add WooCommerce checkout integration note to Event Ticketing description

### PR DESCRIPTION
**Pull request by pippinsplugins**

### CODE REVIEW

**Review by pderksen — APPROVED** [review]

**Review by JJJ — CHANGES_REQUESTED** [review]
How about something like this instead?

> Easily integrates with WooCommerce to allow event tickets to be purchased through existing WooCommerce checkout pages.

My thinking is that we will get more people with existing WooCommerce installs bolting this in as opposed to people replacing our checkout with Woo afterwards, and it may be a good idea to gently tailor the verbiage towards a specific’ish audience.

What do you think?

**Comment by pderksen** [comment]
@JJJ Works for me.

**Comment by pippinsplugins** [comment]
@JJJ changes made, take a look now!

**Comment by JJJ** [comment]
Merged into master. I'll merge these into the 2.1.0 branch and make sure they get committed to wporg with the next deployment there. 👍

**Pull request merged**
