### PR TITLE
Move Requirements_Check to a clean class file

### PR DESCRIPTION
**Pull request by szepeviktor**
A very simple change: Requirements_Check received its own class file.

The single change is

```php
	public function __construct( $main_file ) {

		// Setup file & base
		$this->file = $main_file;
```

### CODE REVIEW

**Comment by szepeviktor** [comment]
A nice smile :)

kép

**Comment by JJJ** [comment]
Hey there @szepeviktor, thanks for this PR. We are likely to merge this in the near future.

Currently, this class provides a PHP5.2 friendly plugin loader, one that intentionally excludes the use of PHP namespaces. Since WordPress has officially bumped its minimum PHP version to 5.6, future versions of the Requirements class can now use them.

Thanks for doing this!

**Comment by JJJ** [comment]
Closing this in favor of #109, which includes a bunch of changes made to the 2.1 branch.

**Comment by szepeviktor** [comment]
> Closing this in favor of #109

@JJJ This is #109 :)

**Comment by JJJ** [comment]
> > Closing this in favor of #109
> 
> @JJJ This is #109 :)

Real sorry. Edited. Should've been #146.

**Pull request closed without merging**
